### ISSUE TITLE
Outline doesnt work on servers

### ISSUE THREAD

**Issue by drimgo** [JackFred2/WhereIsIt#16]
Outline doesnt work on servers, but in singleplayer outline works good

**Comment by JackFred2** [comment]
Does the server have the mod installed? It needs the mod to search the chests for the client.

**Comment by drimgo** [comment]
> Does the server have the mod installed? It needs the mod to search the chests for the client.

Sorry, i thought this mod works without server mod

**Comment by JackFred2** [comment]
That's fine, you may be interested in [Chest Tracker](https://www.curseforge.com/minecraft/mc-mods/chest-tracker).
