### ISSUE TITLE
Joining server crashes game with this mod showing an error in log

### ISSUE THREAD

**Issue by keatit71** [JackFred2/WhereIsIt#17]
after putting more items in a tracked chest the game crashed and now i can;t rejoin the server 
[latest.log](https://github.com/JackFred2/WhereIsIt/files/7833593/latest.log)

**Comment by JackFred2** [comment]
[Update Chest Tracker to 1.1.8](https://www.curseforge.com/minecraft/mc-mods/chest-tracker/files/3593996); you don't need to install Where Is It seperately if using Chest Tracker as it is bundled.
