### ISSUE TITLE
/whereis inconsistency

### ISSUE THREAD

**Issue by nco2k** [JackFred2/WhereIsIt#30]
when you go to your inventory and press Y over an item, the chests will get highlighted, the items inside the chests will get highlighted, and the items inside your inventory will get highlighted. when you use the /whereis command, only the chests will get highlighted, but not the items inside the chests or your inventory. for consistency reasons it would be good if those could get highlighted as well.

**Comment by JackFred2** [comment]
Can do; normally when a request is initiated it caches the search request client side then uses that to highlight items but since the command is server-side theres nothing to cache. I'll have it send back a request to use if needed
