### ISSUE TITLE
Colors out of sync

### ISSUE THREAD

**Issue by nco2k** [JackFred2/WhereIsIt#31]
highlighted chests change their colors synchronously, but highlighted items inside the chests and your inventory are completely out of sync. it looks like every slot has its own timer. for consistency reasons it would be good if you could make them sync up together with the chests.

**Comment by JackFred2** [comment]
This is a personal stylistic choice; the highlight colour is based on the current time and the x coordinate of the slot. It's also partly to prevent the whole GUI flashing when the gradient sharply changes.

**Comment by nco2k** [comment]
but why not give us the option? i would pick flashing of the same color over rgb chaos any day.

i didnt realize that its getting synced by column, because i only spread out the items in one row while testing. if you made this configurable, then you could offer multiple options like: sync by column (default), sync by row, sync with chest, not sync at all (random).

i really like that this mod is highly configurable, so it would be a shame to not have these options.
