### ISSUE TITLE
Color cycle time

### ISSUE THREAD

**Issue by nco2k** [JackFred2/WhereIsIt#32]
it would be cool if we could set a time for how fast the selected color scheme will cycle trough.

**Comment by JackFred2** [comment]
implemented in next release, you're looking for 'Slot Highlight Mouse Factor', 'Slot Highlight X Factor', and 'Highlight Time Factor' in the config

**Comment by nco2k** [comment]
> implemented in next release...

thank you! i really appreciate your work. these changes allow for some nice and interesting effects. :)

btw in the options you wrote "Slot **h**ightlight X Position Factor" with a lowercase **h** instead of an uppercase **H**.
