### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by INV-PLA** [JackFred2/WhereIsIt#34]
[latest (1).log](https://github.com/JackFred2/WhereIsIt/files/13432799/latest.1.log)

**Comment by INV-PLA** [comment]
1.20.1
2.0.22
2.0.24

**Comment by JackFred2** [comment]
I haven't updated Where Is It for 1.20.1 for a bit as I plan to backport the 1.20.2 version in the future.

I will push an update now for 1.20.1 which includes a fix, by updating the required JackFredLib module.

**Comment by JackFred2** [comment]
https://modrinth.com/mod/where-is-it/version/2.2.5+1.20.1
