### ISSUE TITLE
Crash with overlay mods

### ISSUE THREAD

**Issue by bubin7766** [JackFred2/WhereIsIt#35]
Hello not sure if this is a priority for you but when using this mod with the Connector Beta on neoforge it seems to crash with dynamic crosshair installed when pressing Y to search in chests.

I've noticed it cited this below when crashing and it seems to have to do with your mod in some way? I've attached the log from the launcher showing the rest

> [14:32:13] [Render thread/WARN] [ne.mi.co.ForgeHooks/WP]: The following mods have version differences that were not resolved:
jackfredlib_extracommandsourcedata (version 1.1.01.20.1 -> MISSING)
jackfredlib_lying (version 0.5.11.20.1 -> MISSING)
mixinextras (version 0.3.1 -> 0.2.0-beta.8)
Things may not work well.
[14:32:13] [Render thread/INFO] [ARRP/FileResourcePackProviderMixin/]: ARRP register - before user
[14:32:13] [Render thread/WARN] [minecraft/MinecraftServer]: Missing data pack mod:jackfredlib_lying
[14:32:13] [Render thread/WARN] [minecraft/MinecraftServer]: Missing data pack mod:jackfredlib_extracommandsourcedata

Tested with:
Prism Launcher 8.0
Minecraft 1.20.1
NeoForge 47.1.84
Sinytra Connector Beta 31
Connector Extras 1.80
Forgified Fabric API 0.90.7+1.10.3

[latest.log](https://github.com/JackFred2/WhereIsIt/files/13746639/latest.log)

**Comment by JackFred2** [comment]
From what I can tell, dynamic crosshairs bundles an old version of mixin extras (0.2.0-beta.8), and the issue is this old version gets selected by either NeoForge or Connector's dependency resolution instead of the latest one bundled with connector, which causes the two libs which require `mixinextras >= 0.2.0` to not load and crash.

I can't get the dependency overrides to work on connector, so I'll removes the `requires` from the library modules.

![image](https://github.com/JackFred2/WhereIsIt/assets/8350692/8a8a081b-9c12-4ca4-82bb-4f29e6ce545c)

**Comment by bubin7766** [comment]
Is this something i can try and fix myself by utilizing my custom fabric_loader_dependencies.json?

**Comment by JackFred2** [comment]
You'd need to remove `mixinextras` from `jackfredlib-lying` and `jackfredlib-extracommandsourcedata`'s `depends` blocks. I think the dashes get converted to underscores under connector.

I've manually modified a Where Is It jar to do this; you can use it instead until I push an update if you want.
[whereisit-2.3.1+1.20.1+modifiedmixinextras.jar.zip](https://github.com/JackFred2/WhereIsIt/files/13747149/whereisit-2.3.1%2B1.20.1%2Bmodifiedmixinextras.jar.zip)

**Comment by bubin7766** [comment]
Man you're awesome! Thanks for the quick response and all :) This was an undiscovered gem i found and it's definitely going to be a must have mod from here on

**Comment by bubin7766** [comment]
I noticed you published the update [here](https://github.com/JackFred2/WhereIsIt/releases/tag/v2.3.2%2B1.20.1) but i also noticed while the header says 1.20.1 the files themselves are for 1.20.4 making it not show up in the update checker for launchers

**Comment by JackFred2** [comment]
Good catch; I need to update my build scripts to prevent this. Started a proper release for 1.20.1
