### ISSUE TITLE
Chest highlighting bugs out when far away

### ISSUE THREAD

**Issue by bruh1273** [JackFred2/WhereIsIt#36]
**Mod Version**
2.3.3 1.20.4

**Describe the bug**
Highlighting chests when you are very far out (10mil+ blocks) will bug out the rendering and move the render in weird places instead of just on the chest, like it's supposed to be.

**Expected behavior**
The chest highlights precise, and on the exact block it's on, without glitching out all over the place.
**To Reproduce**
Steps to reproduce the issue - please be as detailed as possible.
Teleport to 16 million in each direction, and then try highlighting a chest. 
**Config (Recommended)**
If possible, please attach the `whereisit.json5` config file, under your game or server's `config` directory. 
No config needed.
Attach this as a file, or use a code pasting site like GitHub Gists or Pastebin.

**Log File (Recommended)**
If possible, please attach the **full** `latest.log` file, under your game or server's `logs` directory. This will show what other mods are installed. 

Attach this as a file, or use a code pasting site like GitHub Gists or Pastebin.

**Screenshots (Optional)**
If relevant, an image of the bug in-action.

**Comment by JackFred2** [comment]
fixed in 2.4.3
