### ISSUE TITLE
crashes the server on connector

### ISSUE THREAD

**Issue by Xplodin** [JackFred2/WhereIsIt#37]
**Mod Version**
2.4.0+1.20.1
**Describe the bug**
pressing the search key will crash the server
**To Reproduce**
Steps to reproduce the crash - please be as detailed as possible.
search for an item while its in your inventory
**Config (Recommended)**
If possible, please attach the `whereisit.json5` config file, under your game or server's `config` directory. 
https://gist.github.com/Xplodin/7742fd9cc954f45ea072534c459acfbf
Attach this as a file, or use a code pasting site like GitHub Gists or Pastebin.

**Crash Report**
Attach the **full** `crash-(date).txt` file, under your game or server's `crash-reports` directory. This will show what other mods are installed, and what part of the code crashes.

Attach this as a file, or use a code pasting site like GitHub Gists or Pastebin.

https://gist.github.com/Xplodin/8d0e41619acf27c0add1e137e1d23b7b

says something about getting a server config on client

**Comment by JackFred2** [comment]
fixed in 2.4.3, should only need an update on server

**Comment by Xplodin** [comment]
that was fast! Amazing job!
