### ISSUE TITLE
Why a max on search radius?

### ISSUE THREAD

**Issue by kristianbinau** [JackFred2/WhereIsIt#4]
Hey!
Why is there a limit to max search radius? Shouldn't this be up to each server owner?
I usually build very long chest rooms (80+ blocks), and it's kinda annoying to have to search 4 times to find the right things.

Anyway, thanks for this awesome mod.

**Comment by JackFred2** [comment]
Hey,
There's a max mainly for performance reasons. I'll increase the max to 32 radius; I'm wary of the server performance taking a dive if a large enough area of chunks are searched (121 chunks as a worst case for a radius of 80, for example).

**Comment by kristianbinau** [comment]
Yeah, i totally understand. I just think that there shouldn't be a hard limit. Maybe a warning instead. 

If I wanted to I should be able to change it to 4000 blocks. Yeah, the server would probably crash, but that would be my fault only.

**Comment by JackFred2** [comment]
I get that, I just don't want to give the impression that the mod supports very large radiuses and then have it lag or crash significantly. I'll keep it at 32 blocks for now, and see how well it works.
